export const mkCvData = {
  Summary: {
    [CvQuery.frontend]: [
      "I am a Frontend Developer with over 10 years of experience, I specialize in Vue/Nuxt, but I do not shy away from the occasional React or Typescript project. On the backend, I am a NodeJS developer to the bitter end. Just because I can share types between reports. On the management side, I am holding an up to date PSM and SAFe 6.1 certifications. One of my proudest achievements is leading a project that positioned my startup as a semifinalist in the Preactilerator Chivas the Venture in 2016, where my partner became a TEDx speaker.",

      "I am a Frontend Developer with over 10 years of experience, I specialize in Vue/Nuxt, but I do not shy away from the occasional React or Typescript project. On the backend, I am a NodeJS developer to the bitter end. Just because I can share types between reports. On the management side, I am holding an up to date PSM and SAFe 6.1 certifications. Colleagues often describe me as a builder of innovative digital solutions, and an effective organizer. Someone who can develop MVPs, learn from them and create plans for scaling. I understand the importance of delivering and testing features with real users in increments. One of my proudest achievements is leading a project that positioned my startup as a semifinalist in the Preactilerator Chivas the Venture in 2016, where my partner became a TEDx speaker. I am grateful for the opportunity to work with amazing international teams on various projects, from financial software in fintech companies like Verifone to medical hardware with Onera Health, and AI for health medical devices. I have learned that the greatest asset is the team.",

      "I am a Frontend Developer with over 10 years of experience, I am a big fan of Vue 3/Nuxt, but I do not shy away from the occasional React or Typescript project. On the backend, I am a NodeJS developer to the bitter end. Just because I can share types between Git reports. On the management side, I am holding an up to date PSM and SAFe 6.1 certifications. Colleagues often describe me as a builder of innovative digital solutions, and an effective organizer. Someone who can develop MVPs, learn from them and create plans for scaling. I understand the importance of delivering and testing features with real users in increments. By day, I am a dedicated Developer; by night, I build startups. One of my proudest achievements is leading a project that positioned my startup as a semifinalist in the Preactilerator Chivas the Venture in 2016, where my partner became a TEDx speaker. I am grateful for the opportunity to work with amazing international teams on various projects, from financial software in fintech companies like Verifone to medical hardware with Onera Health, and AI for health medical devices. I have learned that the greatest asset is the team. As a Senior Developer, I am dedicated to creating and mentoring teams to achieve their highest potential. While I recognize my limitations, I always focus on fostering a collaborative and productive environment, delivering high-quality code in testable increments, and leveraging continuous integration pipelines to better the deployment. My main motivation is to create the best experience for my clients. I am excited to work with you on your next project.",
    ],
    [CvQuery.scrum]: [
      "I am a Scrum Master with over 5 years of experience, holding PSM and SAFe 6.1 certifications. With a solid background in software development spanning more than 10 years, I transitioned into the Scrum Master role after earning my Master's in Business from the Polytechnic University of Bucharest. Colleagues often describe me as a builder of innovative digital solutions, an effective organizer, and someone who can develop MVPs, learn from them, and create plans for scaling. I understand the importance of delivering and testing features with real users in increments. By day, I am a dedicated Scrum Master; by night, I build startups. One of my proudest achievements is leading a project that positioned my startup as a semifinalist in the Preactilerator Chivas the Venture in 2016, where my partner became a TEDx speaker.",

      "I am a Scrum Master with over 5 years of experience, holding PSM and SAFe 6.1 certifications. With a solid background in software development spanning more than 10 years, I transitioned into the Scrum Master role after earning my Master's in Business from the Polytechnic University of Bucharest. Colleagues often describe me as a builder of innovative digital solutions, an effective organizer, and someone who can develop MVPs, learn from them, and create plans for scaling. I understand the importance of delivering and testing features with real users in increments. By day, I am a dedicated Scrum Master; by night, I build startups. One of my proudest achievements is leading a project that positioned my startup as a semifinalist in the Preactilerator Chivas the Venture in 2016, where my partner became a TEDx speaker. I am grateful for the opportunity to work with amazing international teams on various projects, from financial software in fintech companies like Verifone, to medical hardware with Onera Health, and AI for health medical devices.",
      
      "I am a Scrum Master with over 5 years of experience, holding PSM and SAFe 6.1 certifications. With a solid background in software development spanning more than 10 years, I transitioned into the Scrum Master role after earning my Master's in Business from the Polytechnic University of Bucharest. Colleagues often describe me as a builder of innovative digital solutions, an effective organizer, and someone who can develop MVPs, learn from them, and create plans for scaling. I understand the importance of delivering and testing features with real users in increments. By day, I am a dedicated Scrum Master; by night, I build startups. One of my proudest achievements is leading a project that positioned my startup as a semifinalist in the Preactilerator Chivas the Venture in 2016, where my partner became a TEDx speaker. I am grateful for the opportunity to work with amazing international teams on various projects, from financial software in fintech companies like Verifone, to medical hardware with Onera Health, and AI for health medical devices. I have learned that the greatest asset is the team. As a Scrum Master, I am dedicated to creating and mentoring teams to achieve their highest potential. While I recognize my limitations, I always focus on fostering a collaborative and productive environment, delivering high-quality code in testable increments, and leveraging continuous integration pipelines.  My main motivation is to create the best experience for my clients. I am excited to work with you on your next project.",
    ]

  }
}